name: Minecraft-LDAP
version: 0.9.9
description: LDAP authentication and (eventually, maybe) authorization for minecraft
authors: [bunny]
website: http://acm.umn.edu, http://github.org/Minecraft-LDAP/

main: edu.umn.acm.minecraft.ldap.MinecraftLDAP
load: startup
database: false
